CREATE TABLE genomics_species (
    id INT AUTO_INCREMENT PRIMARY KEY,
    scientific_name VARCHAR(255) NOT NULL,
    common_name VARCHAR(255),
    genus VARCHAR(255) NOT NULL,
    genome_type VARCHAR(255),
    genome_size VARCHAR(50),
    chromosome_number VARCHAR(50),
    gene_number VARCHAR(50),
    cds_number VARCHAR(50),
    description TEXT,
    image_url VARCHAR(255),
    genomic_sequence VARCHAR(255),
    cds_sequence VARCHAR(255),
    gff3_annotation VARCHAR(255),
    peptide_sequence VARCHAR(255),
    reference_link VARCHAR(255),
    status ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
    submitted_by INT,
    reviewed_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (submitted_by) REFERENCES users(id),
    FOREIGN KEY (reviewed_by) REFERENCES users(id)
);